# Generated by Django 6.0.2 on 2026-03-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
