# Generated by Django 6.0.2 on 2026-04-23 16:34 (manually edited to backfill codes)

import secrets
import string
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

ALPHABET = string.ascii_uppercase + string.digits


def backfill_referral_codes(apps, schema_editor):
    """Assign a unique referral code to every existing user that lacks one."""
    User = apps.get_model('user_authentication', 'User')
    db_alias = schema_editor.connection.alias
    used = set()

    for user in User.objects.using(db_alias).filter(referral_code=''):
        for _ in range(20):
            code = ''.join(secrets.choice(ALPHABET) for _ in range(8))
            if code not in used and not User.objects.using(db_alias).filter(referral_code=code).exists():
                used.add(code)
                user.referral_code = code
                user.save(using=db_alias, update_fields=['referral_code'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        # Step 1: Add column WITHOUT unique constraint + other fields
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=8, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='referral_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='referrals',
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        # Step 2: Backfill unique codes for all existing users
        migrations.RunPython(backfill_referral_codes, migrations.RunPython.noop),

        # Step 3: Now it's safe to add the unique constraint
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
