# Generated by Django 6.0.2 on 2026-03-19 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories_management', '0001_initial'),
        ('products_management', '0002_product_is_listed_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories_management.category'),
        ),
    ]
