# Generated by Django 6.0.2 on 2026-03-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_management', '0004_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_back',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_side',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
