# Generated by Django 6.0.2 on 2026-03-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_management', '0005_product_image_back_product_image_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('pant', 'Pant'), ('tees', 'Tees'), ('shorts', 'Shorts')], default='shirt', max_length=20),
            preserve_default=False,
        ),
    ]
