# Generated by Django 6.0.2 on 2026-04-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_management', '0006_alter_product_description_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('pant', 'Pant'), ('tees', 'Tees'), ('shorts', 'Shorts'), ('coat', 'Coat')], max_length=20),
        ),
    ]
