# Generated by Django 6.0.2 on 2026-04-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
