# Generated by Django 6.0.2 on 2026-04-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_returnrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='shipping_address',
        ),
    ]
