# Generated by Django 6.0.2 on 2026-04-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='refund_processed',
            field=models.BooleanField(default=False),
        ),
    ]
