# Generated by Django 6.0.2 on 2026-04-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_orderitem_refund_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_referral_rewarded',
            field=models.BooleanField(default=False),
        ),
    ]
