# Generated by Django 6.0.2 on 2026-04-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_is_referral_rewarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='refund_processed',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='return_qty',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancelled_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refunded_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('placed', 'Pending'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return_requested', 'Return Requested'), ('returned', 'Returned')], default='placed', max_length=20),
        ),
    ]
