# Generated by Django 6.0.2 on 2026-04-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_orderitem_refund_processed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='refunded_quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refund_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_qty',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
