# Generated by Django 6.0.2 on 2026-04-21 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_management', '0003_couponusage'),
        ('orders', '0009_alter_order_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponusage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='couponusage',
            old_name='used_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='couponusage',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='orders.order'),
        ),
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together={('user', 'coupon', 'order')},
        ),
    ]
