# Generated by Django 6.0.2 on 2026-03-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='image_url',
        ),
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
