# Generated by Django 6.0.2 on 2026-03-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants_management', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='detail',
            field=models.ImageField(blank=True, null=True, upload_to='variants/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='texture',
            field=models.ImageField(blank=True, null=True, upload_to='variants/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='zoom',
            field=models.ImageField(blank=True, null=True, upload_to='variants/'),
        ),
    ]
