# Generated by Django 6.0.2 on 2026-03-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variants_management', '0004_productimage_detail_productimage_texture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='texture',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='zoom',
        ),
    ]
