# Generated by Django 6.0.2 on 2026-03-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variants_management', '0005_remove_productimage_detail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
