# Generated by Django 6.0.2 on 2026-03-24 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants_management', '0006_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variant',
            name='color',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='variant',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
